#更多规则使用说明请参考 http://AppOpt.suto.top

# 网易云后台播放子进程绑定到CPU0,1,5,6
# com.netease.cloudmusic:play=0-1,5-6

# 抖音主线程绑定到中大核
# com.ss.android.ugc.aweme{RenderThread}=6-7

# 注意！上述2条规则仅作为用法参考实例
# 后续添加的规则请不要带#号
（ # 号或 // 开头的规则实际不会生效）

# 语义核心用法：
# e-core           表示能效小核 Efficient-cores
# p-core           表示性能中核 Performance cores
# hp-core          为高性能大核 High Performance cores
# all-core          表示所有核心

# 也可以组合一起用（英文逗号）：
# e-core,p-core  为小核与中核
# p-core,hp-core 为中核与大核

// 日常应用

# 将 '微信' 渲染线程与主线程绑定到中大核
com.tencent.mm=e-core,p-core {
	RenderThread=hp-core
	com.tencent.mm=p-core,hp-core
}

# 将 '微信' 消息推送进程绑定到小核
com.tencent.mm:push=e-core

# 将 'QQ' 主线程与渲染线程绑定到中大核
com.tencent.mobileqq {
	encent.mobileqq=p-core,hp-core
	RenderThread=hp-core
}

# 将 'QQ' 消息推送进程绑定到小核
com.tencent.mobileqq:MSF=e-core

# 将 '淘宝' 主线程绑定到大核
com.taobao.taobao {
	m.taobao.taobao=hp-core
	RenderThread=p-core,hp-core
}

# 将 '酷安' 渲染线程绑定到大核
com.coolapk.market {
	RenderThread=hp-core
	.coolapk.market=p-core,hp-core
}

# 将 '抖音' 关键线程绑定到中大核
com.ss.android.ugc.aweme {
	main=hp-core
	RenderThread=hp-core
	droid.ugc.aweme=p-core,hp-core
}

# 将 '支付宝' 渲染线程、主线程与扫一扫线程绑定到中大核
com.eg.android.AlipayGphone {
	RenderThread=hp-core
	id.AlipayGphone=p-core,hp-core
	ScanRecognize=hp-core
}

# 将 '高德地图' 渲染线程与主线程绑定到中大核
com.autonavi.minimap {
	RenderThread=hp-core
	utonavi.minimap=p-core,hp-core
}

# 将 'Android图形显示组件'渲染引擎线程绑定到大核
surfaceflinger{RenderEngine}=hp-core

# 允许 'Android图形显示组件' 使用所有CPU核心all_core
surfaceflinger=all-core

# 将 '系统界面' 渲染引擎线程与主线程绑定到中大核
com.android.systemui {
	RenderThread=hp-core
	ndroid.systemui=p-core,hp-core
}

// 游戏规则

# 将 '王者荣耀' Unity引擎线程绑定到中大核
com.tencent.tmgp.sgame {
	UnityMain=hp-core
	UnityGfxDeviceW=p-core,hp-core
}

# 将 '和平精英' 主线程绑定到中大核
com.tencent.tmgp.pubgmhd {
	Thread-[0-9]?=hp-core
	Thread-?=hp-core
	RenderThread*=p-core,hp-core
	RHIThread=e-core,p-core
}

# 将 '蛋仔派对' 主线程绑定到大核
com.netease.party {
	MainThread=hp-core
	Compute*=p-core,hp-core
}

# 将 '原神' Unity引擎线程绑定到中大核
com.miHoYo.Yuanshen {
	UnityMain=hp-core
	UnityGfx*=p-core,hp-core
}

# '三角洲行动' 主线程绑定到大核
com.tencent.tmgp.dfm {
	GameThread=hp-core
	Thread*=p-core,hp-core
	TaskGraphNP*=p-core,hp-core
	AudioTrack=e-core
}

# '金铲铲' Unity线程绑定到大核
com.tencent.jkchess=e-core,p-core {
	UnityMain=hp-core
	UnityGfx*=p-core,hp-core
}

# '第五人格' 主线程绑定到大核
com.netease.dwrg {
	Thread-*=p-core,hp-core
	NativeThread=p-core,hp-core
}
